version: "3.9"

services:

  sql1:
    container_name: medicalofficesql
    image: ${GHCR_IMAGE_SQL}
    environment:
      - ACCEPT_EULA=${ACCEPT_EULA}
      - SA_PASSWORD=${SA_PASSWORD}
    ports:
      - "${SQL_PORT}:1433"
    volumes:
      - medical_office_sql_data:/var/opt/mssql
    restart: always

  seq:
    image: datalust/seq:latest
    container_name: MedicalOfficeSeq
    environment:
      - ACCEPT_EULA=${ACCEPT_EULA}
    ports:
      - "${SEQ_PORT}:80"
    depends_on:
      - sql1
    restart: always

  medicalofficeapi:
    image: ${GHCR_IMAGE_API}
    container_name: medicalofficewebapi
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    ports:
      - "${API_HTTP_PORT}:8080"
      - "${API_HTTPS_PORT}:8081"
    depends_on:
      - sql1
      - seq
    command: /bin/sh -c "sleep 30 && dotnet Medical.Office.Api.dll"
    restart: always

  frontend:
    image: ${GHCR_IMAGE_FRONTEND}
    container_name: medicalofficewebclient
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - medicalofficeapi
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "${PROMETHEUS_PORT}:9090"
    depends_on:
      - medicalofficeapi
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
    restart: always

volumes:
  medical_office_sql_data:
  grafana-storage:
