services:

  sql1:
    container_name: medicalofficesql
    image: ghcr.io/raptor057/medicalofficesql:latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - medical_office_sql_data:/var/opt/mssql
    restart: always

  seq:
    image: datalust/seq:latest
    container_name: MedicalOfficeSeq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
    depends_on:
      - sql1
    restart: always

  medicalofficeapi:
    image: ghcr.io/raptor057/medicalofficewebapi:latest
    container_name: medicalofficewebapi
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - sql1
      - seq
    command: /bin/sh -c "sleep 30 && dotnet Medical.Office.Api.dll"
    restart: always

  frontend:
    image: ghcr.io/raptor057/medicalofficewebclient:latest
    container_name: medicalofficewebclient
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    ports:
      - "3000:80"
    depends_on:
      - medicalofficeapi
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: always
    depends_on:
      - medicalofficeapi

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  medical_office_sql_data:
  grafana-storage:
