services:

  sql1:
    container_name: medicalofficesql
    image: ghcr.io/raptor057/medicalofficesql:latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - medical_office_sql_data:/var/opt/mssql
    restart: always
    healthcheck:
      test: ["CMD", "sqlcmd", "-U", "sa", "-P", "${SA_PASSWORD}", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  seq:
    image: datalust/seq:latest
    container_name: MedicalOfficeSeq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
    depends_on:
      - sql1
    restart: always

  medicalofficeapi:
    image: ghcr.io/raptor057/medicalofficewebapi:latest
    container_name: medicalofficewebapi
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      sql1:
        condition: service_healthy
      seq:
        condition: service_started
    restart: always

  frontend:
    image: ghcr.io/raptor057/medicalofficewebclient:latest
    container_name: medicalofficewebclient
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    ports:
      - "3000:80"
    depends_on:
      - medicalofficeapi
    restart: always

volumes:
  medical_office_sql_data:
