# .github/workflows/generate-installers.yml

name: Generate Installers

on:
  push:
    paths:
      - '**.in'
      - 'CMakeLists.txt'
      - '.env'
      - 'scripts/**'
      - 'generate_installers.sh'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install CMake
        run: sudo apt-get update && sudo apt-get install -y cmake

      - name: Generate installers
        run: bash ./generate_installers.sh

      - name: Upload installers as artifact
        uses: actions/upload-artifact@v4
        with:
          name: installers
          path: installer_output/
