name: Automatic Generate Installers

on:
  push:
    paths:
      - '**.in'
      - 'CMakeLists.txt'
      - '.env.gpg'
      - 'scripts/**'
      - 'scripts/generate_installers.sh'
      - 'docker-compose.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake gnupg

      - name: Crear .env desencriptado desde .env.gpg
        run: |
          echo "$MY_ENV_PASSPHRASE" > pass.txt
          gpg --quiet --batch --yes --passphrase-file pass.txt --output .env .env.gpg
          rm pass.txt
        env:
          MY_ENV_PASSPHRASE: ${{ secrets.MY_ENV_PASSPHRASE }}

      - name: Generar instaladores
        run: bash scripts/generate_installers.sh

      - name: Subir instaladores como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: installers
          path: installer_output/

      - name: Crear GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v1.0.${{ github.run_number }}"
          name: "Medical Office Installer v1.0.${{ github.run_number }}"
          body: "Instaladores automáticos con scripts y .env.gpg"
          files: |
            installer_output/start_osx.sh
            installer_output/start_linux.sh
            installer_output/start_windows.ps1
            installer_output/.env.gpg
            installer_output/docker-compose.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
