name: Generate Windows EXE and ZIP

on:
  workflow_dispatch:

jobs:
  build-windows-exe:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment variables
        run: |
          echo "MY_ENV_PASSPHRASE=${{ secrets.MY_ENV_PASSPHRASE }}" >> $env:GITHUB_ENV

      - name: Install GPG
        run: |
          Invoke-WebRequest -Uri 'https://www.gnupg.org/ftp/gcrypt/binary/gnupg-w32-2.4.4_20231214.exe' -OutFile 'gpg-installer.exe'
          Start-Process -FilePath 'gpg-installer.exe' -ArgumentList '/S' -Wait

      - name: Decrypt .env.gpg
        run: |
          & "C:\Program Files (x86)\GnuPG\bin\gpg.exe" --batch --yes --passphrase "$env:MY_ENV_PASSPHRASE" --output .env --decrypt .env.gpg

      - name: Install Inno Setup
        run: |
          Invoke-WebRequest -Uri 'https://jrsoftware.org/download.php/is.exe' -OutFile 'is.exe'
          Start-Process -FilePath 'is.exe' -ArgumentList "/VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-" -Wait

      - name: Build Windows EXE with Inno Setup
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "scripts/windows/create_installer.iss"
        env:
          MY_ENV_PASSPHRASE: ${{ secrets.MY_ENV_PASSPHRASE }}

      - name: Prepare ZIP contents
        run: |
          mkdir final_package
          Copy-Item installer_output\MedicalOfficeInstaller.exe final_package\
          Copy-Item docker-compose.yml final_package\
          Copy-Item .env.gpg final_package\
          Copy-Item scripts\start_windows.ps1 final_package\
          Copy-Item scripts\windows\wrapper.ps1 final_package\

      - name: Create ZIP
        run: Compress-Archive -Path final_package\* -DestinationPath medical-office-windows-package.zip

      - name: Upload ZIP as artifact
        uses: actions/upload-artifact@v4
        with:
          name: medical-office-windows-package
          path: medical-office-windows-package.zip
