name: Automatic Generate Installers

on:
  push:
    paths:
      - '**.in'
      - 'CMakeLists.txt'
      - '.env'
      - 'scripts/**'
      - 'generate_installers.sh'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          echo "GHCR_USERNAME=raptor057" >> .env
          echo "GHCR_PAT=${{ secrets.GHCR_PAT }}" >> .env
          echo "SA_PASSWORD=${{ secrets.SA_PASSWORD }}" >> .env
          echo "ASPNETCORE_ENVIRONMENT=Production" >> .env
          echo "NEXT_PUBLIC_API_URL=http://localhost:8080" >> .env

      - name: Install CMake
        run: sudo apt-get update && sudo apt-get install -y cmake

      - name: Generate installers
        run: bash scripts/generate_installers.sh

      - name: Upload installers as artifact
        uses: actions/upload-artifact@v4
        with:
          name: installers
          path: installer_output/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v1.0.${{ github.run_number }}"
          name: "Medical Office Installer v1.0.${{ github.run_number }}"
          body: "Instaladores generados automáticamente desde GitHub Actions"
          files: |
            installer_output/start_linux.sh
            installer_output/start_osx.sh
            installer_output/start.ps1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
